In [32]:
# Import required libraries and dependencies
import pandas as pd
import hvplot.pandas
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [33]:
# Load the data into a Pandas DataFrame
df_market_data = pd.read_csv(
    "Resources/crypto_market_data.csv",
    index_col="coin_id")

# Display sample data
df_market_data.head(10)

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y
coin_id,,,,,,,
bitcoin,1.08388,7.60278,6.57509,7.67258,-3.25185,83.51840,37.51761
ethereum,0.22392,10.38134,4.80849,0.13169,-12.88890,186.77418,101.96023
tether,-0.21173,0.04935,0.00640,-0.04237,0.28037,-0.00542,0.01954
ripple,-0.37819,-0.60926,2.24984,0.23455,-17.55245,39.53888,-16.60193
bitcoin-cash,2.90585,17.09717,14.75334,15.74903,-13.71793,21.66042,14.49384
binancecoin,2.10423,12.85511,6.80688,0.05865,36.33486,155.61937,69.69195
chainlink,-0.23935,20.69459,9.30098,-11.21747,-43.69522,403.22917,325.13186
cardano,0.00322,13.99302,5.55476,10.10553,-22.84776,264.51418,156.09756
litecoin,-0.06341,6.60221,7.28931,1.21662,-17.23960,27.49919,-12.66408
bitcoin-cash-sv,0.92530,3.29641,-1.86656,2.88926,-24.87434,7.42562,93.73082

In [34]:
# Generate summary statistics
df_market_data.describe()

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y
count,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000
mean,-0.269686,4.497147,0.185787,1.545693,-0.094119,236.537432,347.667956
std,2.694793,6.375218,8.376939,26.344218,47.365803,435.225304,1247.842884
min,-13.527860,-6.094560,-18.158900,-34.705480,-44.822480,-0.392100,-17.567530
25%,-0.608970,0.047260,-5.026620,-10.438470,-25.907990,21.660420,0.406170
50%,-0.063410,3.296410,0.109740,-0.042370,-7.544550,83.905200,69.691950
75%,0.612090,7.602780,5.510740,4.578130,0.657260,216.177610,168.372510
max,4.840330,20.694590,24.239190,140.795700,223.064370,2227.927820,7852.089700

In [35]:
# Plot your data to see what's in your DataFrame
df_market_data.hvplot.line(
    width=800,
    height=400,
    rot=90
)

:NdOverlay   [Variable]
   :Curve   [coin_id]   (value)

---

### Prepare the Data

In [36]:
# Use the `StandardScaler()` module from scikit-learn to normalize the data from the CSV file
scaled_data = StandardScaler().fit_transform(df_market_data[["price_change_percentage_24h",
                                                             "price_change_percentage_7d",
                                                             "price_change_percentage_14d",
                                                             "price_change_percentage_30d",
                                                             "price_change_percentage_60d",
                                                             "price_change_percentage_200d",
                                                             "price_change_percentage_1y"
                                                             ]])
scaled_data[:5]

array([[ 0.50852937,  0.49319307,  0.77220043,  0.23545963, -0.0674951 ,
        -0.35595348, -0.25163688],
       [ 0.18544589,  0.93444504,  0.55869212, -0.05434093, -0.27348273,
        -0.11575947, -0.19935211],
       [ 0.02177396, -0.70633685, -0.02168042, -0.06103015,  0.00800452,
        -0.55024692, -0.28206051],
       [-0.04076438, -0.81092807,  0.24945797, -0.05038797, -0.37316402,
        -0.45825882, -0.29554614],
       [ 1.19303608,  2.00095907,  1.76061001,  0.54584206, -0.29120287,
        -0.49984776, -0.27031695]])

In [37]:
# Create a DataFrame with the scaled data
scaled_df = pd.DataFrame(scaled_data, columns=["price_change_percentage_24h",
                                               "price_change_percentage_7d",
                                                "price_change_percentage_14d",
                                                "price_change_percentage_30d",
                                                "price_change_percentage_60d",
                                                "price_change_percentage_200d",
                                                "price_change_percentage_1y"
                                                ])

# Copy the crypto names from the original DataFrame
scaled_df['coin_id'] = df_market_data.index

# Set the coin_id column as index
scaled_df = scaled_df.set_index("coin_id")

# Display the scaled DataFrame
scaled_df.head()

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y
coin_id,,,,,,,
bitcoin,0.508529,0.493193,0.772200,0.235460,-0.067495,-0.355953,-0.251637
ethereum,0.185446,0.934445,0.558692,-0.054341,-0.273483,-0.115759,-0.199352
tether,0.021774,-0.706337,-0.021680,-0.061030,0.008005,-0.550247,-0.282061
ripple,-0.040764,-0.810928,0.249458,-0.050388,-0.373164,-0.458259,-0.295546
bitcoin-cash,1.193036,2.000959,1.760610,0.545842,-0.291203,-0.499848,-0.270317

---

### Find the Best Value for k Using the Original Scaled DataFrame.

In [38]:
# Create a list with the number of k-values from 1 to 11
k = list(range(1,12))

In [39]:
# Create an empty list to store the inertia values
inertia = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_scaled`
# 3. Append the model.inertia_ to the inertia list
for i in k:
    k_model = KMeans(n_clusters=i, random_state=0)
    k_model.fit(scaled_df)
    inertia.append(k_model.inertia_)

In [40]:
# Create a dictionary with the data to plot the Elbow curve
elbow_dict = {
    "k": k,
    "inertia": inertia
}

# Create a DataFrame with the data to plot the Elbow curve
elbow_df = pd.DataFrame(elbow_dict)
elbow_df

     k     inertia
0    1  287.000000
1    2  198.571818
2    3  145.635748
3    4   79.022435
4    5   66.217780
5    6   59.139070
6    7   48.406314
7    8   38.993588
8    9   34.400595
9   10   28.573603
10  11   23.890044

In [41]:
# Plot a line chart with all the inertia values computed with
# the different values of k to visually identify the optimal value for k.
elbow_df_plot = elbow_df.hvplot.line(
    x="k",
    y="inertia",
    title="Elbow Curve",
    xticks=k
)
elbow_df_plot

:Curve   [k]   (inertia)

#### Answer the following question: 

**Question:** What is the best value for `k`?

**Answer:** The "elbow" appears to be at `k=4`. This is the optimal number of clusers. This point suggests that adding more clusters beyond this number provides diminishing returns in explaining variance or reducing error.

---

### Cluster Cryptocurrencies with K-means Using the Original Scaled DataFrame

In [42]:
# Initialize the K-Means model using the best value for k
model = KMeans(n_clusters=4, random_state=0)

In [43]:
# Fit the K-Means model using the scaled DataFrame
model.fit(scaled_df)

KMeans(n_clusters=4, random_state=0)

In [44]:
# Predict the clusters to group the cryptocurrencies using the scaled DataFrame
clusters = model.predict(scaled_df)

# Print the resulting array of cluster values.
print(clusters)

[2 2 0 0 2 2 2 2 2 0 0 0 0 2 0 2 0 0 2 0 0 2 0 0 0 0 0 0 2 0 0 0 1 2 0 0 3
 0 0 0 0]

In [45]:
# Create a copy of the scaled DataFrame
scaled_predict_df = scaled_df.copy()

In [46]:
# Add a new column to the copy of the scaled DataFrame with the predicted clusters
scaled_predict_df['Clusters'] = clusters

# Display the copy of the scaled DataFrame
scaled_predict_df.head()

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y,Clusters
coin_id,,,,,,,,
bitcoin,0.508529,0.493193,0.772200,0.235460,-0.067495,-0.355953,-0.251637,2
ethereum,0.185446,0.934445,0.558692,-0.054341,-0.273483,-0.115759,-0.199352,2
tether,0.021774,-0.706337,-0.021680,-0.061030,0.008005,-0.550247,-0.282061,0
ripple,-0.040764,-0.810928,0.249458,-0.050388,-0.373164,-0.458259,-0.295546,0
bitcoin-cash,1.193036,2.000959,1.760610,0.545842,-0.291203,-0.499848,-0.270317,2

In [47]:
# Create a scatter plot using hvPlot by setting
# `x="price_change_percentage_24h"` and `y="price_change_percentage_7d"`.
# Color the graph points with the labels found using K-Means and
# add the crypto name in the `hover_cols` parameter to identify
# the cryptocurrency represented by each data point.
scaled_predict_df_plot = scaled_predict_df.hvplot.scatter(
    x="price_change_percentage_24h",
    y="price_change_percentage_7d",
    by="Clusters",
    hover_cols="coin_id",
    title="Crypto Clusters, k=4",
)
scaled_predict_df_plot

:NdOverlay   [Clusters]
   :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coin_id)

---

### Optimize Clusters with Principal Component Analysis.

In [48]:
# Create a PCA model instance and set `n_components=3`.
pca = PCA(n_components=3)

In [49]:
# Use the PCA model with `fit_transform` to reduce the original scaled DataFrame
# down to three principal components.
pca_data = pca.fit_transform(scaled_df)

# View the scaled PCA data
pca_data[:5]

array([[-0.60066733,  0.84276006,  0.46159457],
       [-0.45826071,  0.45846566,  0.95287678],
       [-0.43306981, -0.16812638, -0.64175193],
       [-0.47183495, -0.22266008, -0.47905316],
       [-1.15779997,  2.04120919,  1.85971527]])

In [50]:
# Interpret the Loadings: The loadings matrix tells you how much each original feature contributes 
# to each principal component. A higher absolute value of a loading indicates a stronger contribution.
loadings = pca.components_

feature_names = scaled_df.columns
loading_df = pd.DataFrame(loadings, columns=feature_names)

# Add principal component labels (PC1, PC2, ...)
loading_df.index = [f'PC{i+1}' for i in range(loading_df.shape[0])]

# Display the loadings
print(loading_df)

     price_change_percentage_24h  price_change_percentage_7d  \
PC1                    -0.416728                   -0.102432
PC2                     0.358162                    0.227432
PC3                    -0.218795                    0.787670

     price_change_percentage_14d  price_change_percentage_30d  \
PC1                    -0.009162                     0.191523
PC2                     0.540415                     0.562182
PC3                     0.349534                    -0.181744

     price_change_percentage_60d  price_change_percentage_200d  \
PC1                     0.320365                      0.594468
PC2                     0.434040                      0.027735
PC3                    -0.361377                      0.039733

     price_change_percentage_1y
PC1                    0.568379
PC2                   -0.150789
PC3                    0.210541

In [51]:
# Retrieve the explained variance to determine how much information
# can be attributed to each principal component.
print(pca.explained_variance_ratio_)
sum(pca.explained_variance_ratio_)

[0.3719856  0.34700813 0.17603793]

0.8950316570309842

#### Answer the following question: 

**Question:** What is the total explained variance of the three principal components?

**Answer:** The total explained variance for the three principal components is 0.895, or 89.5%. This shows that these three components account for the majority of the variance within the dataset.

In [52]:
# Create a new DataFrame with the PCA data.
market_pca_df = pd.DataFrame(pca_data, columns=["PCA1", "PCA2", "PCA3"])

# Copy the crypto names from the original scaled DataFrame
market_pca_df["coin_id"] = df_market_data.index

# Set the coin_id column as index
market_pca_df = market_pca_df.set_index("coin_id")

# Display the scaled PCA DataFrame
market_pca_df.head()

                  PCA1      PCA2      PCA3
coin_id
bitcoin      -0.600667  0.842760  0.461595
ethereum     -0.458261  0.458466  0.952877
tether       -0.433070 -0.168126 -0.641752
ripple       -0.471835 -0.222660 -0.479053
bitcoin-cash -1.157800  2.041209  1.859715

---

### Find the Best Value for k Using the Scaled PCA DataFrame

In [53]:
# Create a list with the number of k-values from 1 to 11
k = list(range(1,12))

In [54]:
# Create an empty list to store the inertia values
inertia = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_pca`
# 3. Append the model.inertia_ to the inertia list
for i in k:
    k_model = KMeans(n_clusters=i, random_state=0)
    k_model.fit(market_pca_df)
    inertia.append(k_model.inertia_)

In [55]:
# Create a dictionary with the data to plot the Elbow curve
pca_elbow_dict = {
    "k": k,
    "inertia": inertia
}

# Create a DataFrame with the data to plot the Elbow curve
pca_elbow_df = pd.DataFrame(pca_elbow_dict)
pca_elbow_df

     k     inertia
0    1  256.874086
1    2  168.811896
2    3  115.918077
3    4   49.665497
4    5   41.357314
5    6   30.796642
6    7   25.915457
7    8   21.890936
8    9   17.720699
9   10   13.838699
10  11    7.984355

In [56]:
# Plot a line chart with all the inertia values computed with
# the different values of k to visually identify the optimal value for k.
pca_elbow_df_plot = pca_elbow_df.hvplot.line(
    x="k",
    y="inertia",
    title="PCA Elbow Curve",
    xticks=k
)
pca_elbow_df_plot

:Curve   [k]   (inertia)

#### Answer the following questions: 

* **Question:** What is the best value for `k` when using the PCA data?

  * **Answer:** Looking at the elbow curve above, the best value for `k` using the PCA data is 4.


* **Question:** Does it differ from the best `k` value found using the original data?

  * **Answer:** This does not differ from the best value of `k` found using the original data.

### Cluster Cryptocurrencies with K-means Using the Scaled PCA DataFrame

In [57]:
# Initialize the K-Means model using the best value for k
k_model = KMeans(n_clusters=4, random_state=0)

In [58]:
# Fit the K-Means model using the PCA data
k_model.fit(market_pca_df)

KMeans(n_clusters=4, random_state=0)

In [59]:
# Predict the clusters to group the cryptocurrencies using the scaled PCA DataFrame
pca_clusters = k_model.predict(market_pca_df)

# Print the resulting array of cluster values.
pca_clusters

array([2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 3, 0, 0, 0, 0],
      dtype=int32)

In [60]:
# Create a copy of the scaled PCA DataFrame
market_pca_df_copy = market_pca_df.copy()

# Add a new column to the copy of the PCA DataFrame with the predicted clusters
market_pca_df_copy["PCA_Clusters"] = pca_clusters

# Display the copy of the scaled PCA DataFrame
market_pca_df_copy

                          PCA1      PCA2      PCA3  PCA_Clusters
coin_id
bitcoin              -0.600667  0.842760  0.461595             2
ethereum             -0.458261  0.458466  0.952877             2
tether               -0.433070 -0.168126 -0.641752             0
ripple               -0.471835 -0.222660 -0.479053             0
bitcoin-cash         -1.157800  2.041209  1.859715             2
binancecoin          -0.516534  1.388377  0.804071             2
chainlink            -0.450711  0.517699  2.846143             2
cardano              -0.345600  0.729439  1.478013             2
litecoin             -0.649468  0.432165  0.600303             2
bitcoin-cash-sv      -0.759014 -0.201200 -0.217653             0
crypto-com-chain     -0.248198 -1.376252 -1.462026             0
usd-coin             -0.438408 -0.175337 -0.663388             0
eos                  -0.693425 -0.473815 -0.527597             0
monero                0.060499  2.909404  1.498571             2
tron                 -0.393352 -0.108192 -0.012756             0
tezos                -0.796176 -0.494409  1.082812             2
okb                   0.064075 -1.269825 -1.098829             0
stellar              -0.489015 -0.732719 -0.062543             0
cosmos               -0.306272  0.703415  1.714224             2
cdai                 -0.513528 -0.142802 -0.656566             0
neo                  -0.362120 -0.986914 -0.728752             0
wrapped-bitcoin      -0.604265  0.827398  0.439316             2
leo-token            -0.413296 -0.674115 -1.076628             0
huobi-token          -0.407483 -0.212507 -0.351426             0
nem                   0.608974  0.563532 -1.148742             0
binance-usd          -0.450211 -0.151019 -0.647401             0
iota                 -0.764665 -0.517886  0.204990             0
vechain              -0.556315 -1.938209 -1.261776             0
zcash                -0.425147  0.492976  1.058048             2
theta-token           2.676868 -0.013954 -1.965207             0
dash                 -0.613923 -0.479337  0.339565             0
ethereum-classic     -0.579924 -0.356334 -0.114942             0
ethlend               8.089018 -3.896891  2.301382             1
maker                -0.389045  0.165041  0.379414             2
havven                0.865762 -2.261882  0.275583             0
omisego               0.111675  0.428316 -1.205398             0
celsius-degree-token  4.792395  6.767679 -1.986985             3
ontology             -0.632355 -2.108117 -0.652227             0
ftx-token            -0.593142  0.021485  0.209911             0
true-usd             -0.458131 -0.135734 -0.635284             0
digibyte             -0.297910 -0.191126 -0.909602             0

In [61]:
# Create a scatter plot using hvPlot by setting
# `x="PC1"` and `y="PC2"`.
# Color the graph points with the labels found using K-Means and
# add the crypto name in the `hover_cols` parameter to identify
# the cryptocurrency represented by each data point.
market_pca_df_plot = market_pca_df_copy.hvplot.scatter(
    x="PCA1",
    y="PCA2",
    by="PCA_Clusters",
    hover_cols="coin_id",
    title="Crypto Clusters with PCA, k=4",
)
market_pca_df_plot

:NdOverlay   [PCA_Clusters]
   :Scatter   [PCA1]   (PCA2,coin_id)

### Visualize and Compare the Results

In this section, you will visually analyze the cluster analysis results by contrasting the outcome with and without using the optimization techniques.

In [64]:
# Composite plot to contrast the Elbow curves
# use `*` to have both lines in the same plot
elbow_plots = (elbow_df_plot.relabel("Elbow Curve") * pca_elbow_df_plot.relabel("PCA Elbow Curve"))
hvplot.save(elbow_plots, 'images/elbow_plots.png')  
elbow_plots

The geckodriver version (0.35.0) detected in PATH at /opt/anaconda3/envs/dev/bin/geckodriver might not be compatible with the detected firefox version (109.0.1); currently, geckodriver 0.33.0 is recommended for firefox 109.*, so it is advised to delete the driver in PATH and retry

:Overlay
   .Curve.Elbow_Curve     :Curve   [k]   (inertia)
   .Curve.PCA_Elbow_Curve :Curve   [k]   (inertia)

In [65]:
# Composite plot to contrast the clusters
cluster_plots = (scaled_predict_df_plot + market_pca_df_plot).cols(1)
hvplot.save(cluster_plots, 'images/cluster_plots.png')  
cluster_plots

:Layout
   .NdOverlay.I  :NdOverlay   [Clusters]
      :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coin_id)
   .NdOverlay.II :NdOverlay   [PCA_Clusters]
      :Scatter   [PCA1]   (PCA2,coin_id)

#### Answer the following question: 

  * **Question:** After visually analyzing the cluster analysis results, what is the impact of using fewer features to cluster the data using K-Means?

  * **Answer:** 
  
 For both the original data and the PCA data with three components, the best value of `k` is 4. This suggests that a PCA model with three features is appropriate for this data set.

Using fewer features in the PCA model to cluster the data causes the clusters to become more concentrated compared to the original data. Also, in the PCA plot, cluster 3 (`coin_id` = "celsius-degree-token") is distanced from clusters 0 and 2 (each with sevearl different contributing `coin_id`) which is in contrast to the original data plot where cluster 3 appears to be amongst cluster 0. This indicates that there is a primary feature in the original data which is causing coin_id "celsius_degree_token" to have its own cluster.